
name: Deploy project
on: 
    push:
        branches:
            - main

    workflow_dispatch:
        branches:
            - main

jobs:
  test: 
    runs-on: ubuntu-latest
    
    steps:
        - name: Git Code
          uses: actions/checkout@v3

        - name: Install NodeJS
          uses: actions/setup-node@v4
          with: 
            node4-version: 18
        
        - name: Install Dependencies
          run:  npm ci

        - name: Build project
          run:  npm run build
          
        - name: Deploy
          run: echo "Deploying....."

        


